spring:
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5433/books_db
    username: postgres
    password: 123
    hikari:
      schema: books_shelf_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS books_shelf_schema
      connection-timeout: 10000
server:
  port: 8083